# 中間レポート解答例
以下中間レポートをプログラミングで解いてみました. 皆様の理解の助けになれば幸いです. 

このページから分かる通り, 行列の計算や掃き出し法はすでに自動化されていて, 人間が手を動かして計算することはこの授業や院試(大学院に入るための試験)以外にはあまりないと思います. 

## 中間レポート第1問


In [33]:
# 第1問(1)
import numpy as np
ans = np.array([[1,2],[-4,-1],[5,-2]])+ 2 * np.array([[2,-1],[0,4],[-7,0]])
print(ans)

[[ 5  0]
 [-4  7]
 [-9 -2]]


In [34]:
# 第1問(2)
ans = 3 * np.array([[2,-1,4],[0,3,-5]]) \
- 2 * (np.array([[0,1,-2],[7,-5,4]]) - 3 * np.array([[1,-2,6],[4,-1,5]]) )
print(ans)

[[ 12 -17  52]
 [ 10  13   7]]


## 中間レポート第2問

In [35]:
import itertools
X=[0]*5
X[1] = np.array([[-1,2,-5]])
X[2] = np.array([[1,0,2],[0,3,0],[4,0,5]])
X[3] = np.array([[-2,5,3],[1,-3,0]])
X[4] = np.array([[-4],[3],[1]])
box= {1:"A", 2:"B", 3:"C",4:"D"}
for cp in itertools.permutations([1,2,3,4], 2):
    try :
        np.dot(X[cp[0]], X[cp[1]])
        print(box[cp[0]]+box[cp[1]]+"の積は定義できて," + box[cp[0]]+box[cp[1]]+"=")
        print(np.dot(X[cp[0]], X[cp[1]]))   
    except:
        continue

ABの積は定義できて,AB=
[[-21   6 -27]]
ADの積は定義できて,AD=
[[5]]
BDの積は定義できて,BD=
[[ -2]
 [  9]
 [-11]]
CBの積は定義できて,CB=
[[10 15 11]
 [ 1 -9  2]]
CDの積は定義できて,CD=
[[ 26]
 [-13]]
DAの積は定義できて,DA=
[[  4  -8  20]
 [ -3   6 -15]
 [ -1   2  -5]]


## 中間レポート第3問

In [36]:
import sympy as sp
x = sp.sqrt(2)
A=np.array([[2,1],[1,2]])
P = (1/x)*np.array([[1,1],[-1,1]])

In [37]:
# 第3問(1)
print(np.dot(A,A))
print(np.dot(np.dot(A,A),A))

[[5 4]
 [4 5]]
[[14 13]
 [13 14]]


In [38]:
# 第3問(2)
print(np.dot(P.T,P))
print(np.dot(P,P.T))

[[1 0]
 [0 1]]
[[1 0]
 [0 1]]


In [39]:
# 第3問(3)
print(np.dot(np.dot(P.T,A),P))

[[1 0]
 [0 3]]


In [40]:
# 第3問(4)
n = sp.Symbol('n')
print(np.dot(np.dot(P.T,A),P)**n)

[[1 0**n]
 [0**n 3**n]]


In [41]:
# 第3問(5)
X=np.dot(np.dot(P.T,A),P)**n
print(sp.simplify(np.dot(np.dot(P,X),P.T)))

[[0**n + 3**n/2 + 1/2, 3**n/2 - 1/2], [3**n/2 - 1/2, -0**n + 3**n/2 + 1/2]]


## 中間レポート第4問

In [42]:
# 第4問(1)
A=sp.Matrix(np.array([[2,1,-1],[1,1,1],[3,1,-3]]))
print(A.rref())

(Matrix([
[1, 0, -2],
[0, 1,  3],
[0, 0,  0]]), (0, 1))


In [43]:
# 第4問(2)
A=sp.Matrix(np.array([[1,1,5,0,3],[3,1,9,1,8],[2,0,4,1,5],[2,1,7,1,7]]))
print(A.rref())

(Matrix([
[1, 0, 2, 0, 1],
[0, 1, 3, 0, 2],
[0, 0, 0, 1, 3],
[0, 0, 0, 0, 0]]), (0, 1, 3))


In [44]:
# 第4問(3)
A = np.array([np.arange(i, i+5) for i in range(1,6)])
A=sp.Matrix(A)
print(A.rref())

(Matrix([
[1, 0, -1, -2, -3],
[0, 1,  2,  3,  4],
[0, 0,  0,  0,  0],
[0, 0,  0,  0,  0],
[0, 0,  0,  0,  0]]), (0, 1))


## 中間レポート第5問

In [45]:
# 第5問(1)
A = np.array([[1,2,1],[2,3,1],[1,2,2]])
b = np.array([[0],[0],[0]])
chrs = sp.symbols("x_{1:4}", Integer=True)
mat_numpy = np.array(chrs).reshape(3,1)
eq =list((np.dot(A,mat_numpy)-b).reshape(3))
sp.linsolve(eq, chrs)

{(0, 0, 0)}

In [46]:
# 第5問(1)別解
A = np.array([[1,2,1],[2,3,1],[1,2,2]])
b = np.array([[0],[0],[0]])
X=sp.Matrix(np.concatenate([A, b], 1))
print(X.rref())

(Matrix([
[1, 0, 0, 0],
[0, 1, 0, 0],
[0, 0, 1, 0]]), (0, 1, 2))


In [47]:
# 第5問(2)
A = np.array([[1,1,5,0],[2,1,7,1],[3,1,9,1]])
b = np.array([[3],[7],[8]])
chrs = sp.symbols("x_{1:5}", Integer=True)
mat_numpy = np.array(chrs).reshape(4,1)
eq =list((np.dot(A,mat_numpy)-b).reshape(3))
sp.linsolve(eq, chrs)

{(-2*x_{3} + 1, -3*x_{3} + 2, x_{3}, 3)}

In [48]:
# 第5問(2)別解
A = np.array([[1,1,5,0],[2,1,7,1],[3,1,9,1]])
b = np.array([[3],[7],[8]])
X=sp.Matrix(np.concatenate([A, b], 1))
print(X.rref())

(Matrix([
[1, 0, 2, 0, 1],
[0, 1, 3, 0, 2],
[0, 0, 0, 1, 3]]), (0, 1, 3))


In [49]:
# 第5問(3)
A = np.array([[1,1,-2,1,3],[2,-1,2,2,6],[3,2,-4,-3,-9]])
b = np.array([[1],[2],[3]])
chrs = sp.symbols("x_{1:6}", Integer=True)
mat_numpy = np.array(chrs).reshape(5,1)
eq =list((np.dot(A,mat_numpy)-b).reshape(3))
sp.linsolve(eq, chrs)

{(1, 2*x_{3}, x_{3}, -3*x_{5}, x_{5})}

In [50]:
# 第5問(3)別解
A = np.array([[1,1,-2,1,3],[2,-1,2,2,6],[3,2,-4,-3,-9]])
b = np.array([[1],[2],[3]])
X=sp.Matrix(np.concatenate([A, b], 1))
print(X.rref())

(Matrix([
[1, 0,  0, 0, 0, 1],
[0, 1, -2, 0, 0, 0],
[0, 0,  0, 1, 3, 0]]), (0, 1, 3))


## 中間レポート第6問
この問題だけプログラミングできなかった. 一応aの値は推定できるが...

In [22]:
a = sp.Symbol('a')
A = np.array([[1,-2,-1,1,0],[-2,5,3,-2,1],[1,1,2,0,-1],[5,0,5,3,2]])
b = np.array([[0],[-1],[1],[a]])
X=sp.Matrix(np.concatenate([A, b], 1))
print(X.rref())

(Matrix([
[1, 0, 1, 0, (-2*a - 4)/(a + 2), 0],
[0, 1, 1, 0,                  1, 0],
[0, 0, 0, 1,  (4*a + 8)/(a + 2), 0],
[0, 0, 0, 0,                  0, 1]]), (0, 1, 3, 5))


In [23]:
a = sp.Symbol('a')
A = np.array([[1,-2,-1,1,0],[-2,5,3,-2,1],[1,1,2,0,-1],[5,0,5,3,2]])
b = np.array([[0],[-1],[1],[-2]])
X=sp.Matrix(np.concatenate([A, b], 1))
print(X.rref())

(Matrix([
[1, 0, 1, 0, -2,  2],
[0, 1, 1, 0,  1, -1],
[0, 0, 0, 1,  4, -4],
[0, 0, 0, 0,  0,  0]]), (0, 1, 3))


## 中間レポートおまけ問題

おまけ問題(1)(2)の解答は次のとおりである.
(1)の解答は全部で4通りある. 
(2)に関しては全探索して求めれば良い. 計算量は$O(n^{2}2^{n^2})$なので$n=4$なら十分高速で行ける.

In [24]:
import random
import sys
import itertools
import copy

def checker(S):
    total =10**9
    for box in itertools.product([0,1], repeat = l):
        T=copy.deepcopy(S)
        for a in range(len(box)):
            i = a//N
            j = a % N
            if box[a]==1:
                T[i][j] =(T[i][j]+1)%2
                if i > 0:
                    T[i-1][j] = (T[i-1][j] + 1) % 2
                if j > 0:
                    T[i][j-1] = (T[i][j-1] + 1) % 2
                if i < N-1:
                    T[i+1][j] = (T[i+1][j] + 1) % 2
                if j < N-1:
                    T[i][j+1] = (T[i][j+1] + 1) % 2
        if T==[[0]*N for i in range(N)]:
            total = min(total, sum(box))
    if total == 10**9:
        print("この行列は零行列にできない.")
        return -1
    else:
        print("零行列にすることができ, 最小の操作回数は"+str(total))
        for box in itertools.product([0,1], repeat = l):
            if sum(box)!=total:
                continue
            T=copy.deepcopy(S)
            for a in range(len(box)):
                i = a//N
                j = a % N
                if box[a]==1:
                    T[i][j] =(T[i][j]+1)%2
                    if i > 0:
                        T[i-1][j] = (T[i-1][j] + 1) % 2
                    if j > 0:
                        T[i][j-1] = (T[i][j-1] + 1) % 2
                    if i < N-1:
                        T[i+1][j] = (T[i+1][j] + 1) % 2
                    if j < N-1:
                        T[i][j+1] = (T[i][j+1] + 1) % 2
            if T==[[0]*N for i in range(N)]:
                print("操作手順は例えば以下の通り")
                for a in range(len(box)):
                    if box[a]==1:
                        i = a//N
                        j = a % N
                        print("("+str(i+1)+","+str(j+1)+")成分に操作を行う.")
        return total
    
N=4
l = N**2
S = [[0]*N for i in range(N)]
for i in range(N):
    S[i][0]=1
    S[0][i]=1
S[N-1][N-1]=1
total=checker(S) 

零行列にすることができ, 最小の操作回数は6
操作手順は例えば以下の通り
(1,3)成分に操作を行う.
(2,1)成分に操作を行う.
(3,2)成分に操作を行う.
(3,3)成分に操作を行う.
(4,1)成分に操作を行う.
(4,4)成分に操作を行う.
操作手順は例えば以下の通り
(1,2)成分に操作を行う.
(1,4)成分に操作を行う.
(2,3)成分に操作を行う.
(3,1)成分に操作を行う.
(3,3)成分に操作を行う.
(4,4)成分に操作を行う.
操作手順は例えば以下の通り
(1,1)成分に操作を行う.
(2,3)成分に操作を行う.
(2,4)成分に操作を行う.
(3,2)成分に操作を行う.
(4,2)成分に操作を行う.
(4,4)成分に操作を行う.
操作手順は例えば以下の通り
(1,1)成分に操作を行う.
(1,4)成分に操作を行う.
(3,4)成分に操作を行う.
(4,1)成分に操作を行う.
(4,3)成分に操作を行う.
(4,4)成分に操作を行う.


おまけ問題(3)の解答は次のとおりである.
計算量$O(n^6)$ぐらいだと思われる. $n=10$までなら十分高速である. 
本当はPythonのライブラリーを使いたかったが, どうも有限体上での連立一次方程式を解いてくれるライブラリーがなく, 自分で掃き出し法を実装しなければいけなくなった. 

In [25]:
def linear_solve(S):
    A = [[0]*l for i in range(l)]
    B = [0]*l
    for i in range(N):
        for j in range(N):
            B[i*N + j]=S[i][j]
    for a in range (l):
        i = a // N
        j = a % N  
        A[a][a]=1
        A[max(a-1,i*N)][a] = 1
        A[min(a+1,i*N + (N-1))][a] = 1
        if a > N-1:
            A[a-N][a] = 1
        if a < N*(N-1):
            A[a+N][a] = 1
    for a in range(l):
        A[a].append(B[a])

    # l*l+1行列の掃きだし法
    r =0
    q=0
    while q <l:
        flag =True
        for k in range(r,l):
            if A[k][q]!=0:
                flag =False
                break
        if flag:
            q += 1
            continue
        b=A[r]
        A[r] = A[k]
        A[k]=b
        for j in range(l):
            if j != r:
                c = A[j][q]
                for k in range(l+1):
                    A[j][k] = (A[j][k] + c*A[r][k])%2
        r +=1
        q+=1
    for i in range(r, l):
        if A[i][l] !=0:
            print("この行列は零行列にできない.")
            return -1

    s = l - r
    C = [0]*s
    t=0
    for i in range(l):
        if A[i][i]==0:
            C[t]= i
            t+=1

    D = [0]*l
    for i in range(l):
        D[i] = A[i][l]
    
    ans=10**9
    for box in itertools.product([0,1], repeat=s):
        E = copy.deepcopy(D)
        for i in range(len(box)):
            if box[i]==1:
                for k in range(l):
                    E[k]=(E[k] + A[k][C[i]])%2
                E[C[i]]+=1
        ans = min(ans, sum(E))
    print("零行列にすることができ, 最小の操作回数は"+str(ans))
    return ans
#行列Bでの試行例
N=4
l = N**2
S = [[0]*N for i in range(N)]
for i in range(N):
    S[i][0]=1
    S[0][i]=1
S[N-1][N-1]=1
total = linear_solve(S)

零行列にすることができ, 最小の操作回数は6


## おまけ問題の更なる考察
ここから先はおまけ問題のおまけである.
上のプログラミングをちょこっと変えるだけで, ライツアウト(この問題)を解いてくれるプログラムが作れる.

In [26]:
def method_linear_solve(S):
    A = [[0]*l for i in range(l)]
    B = [0]*l
    for i in range(N):
        for j in range(N):
            B[i*N + j]=S[i][j]
    for a in range (l):
        i = a // N
        j = a % N  
        A[a][a]=1
        A[max(a-1,i*N)][a] = 1
        A[min(a+1,i*N + (N-1))][a] = 1
        if a > N-1:
            A[a-N][a] = 1
        if a < N*(N-1):
            A[a+N][a] = 1
    for a in range(l):
        A[a].append(B[a])

    # l*l+1行列の掃きだし法
    r =0
    q=0
    while q <l:
        flag =True
        for k in range(r,l):
            if A[k][q]!=0:
                flag =False
                break
        if flag:
            q += 1
            continue
        b=A[r]
        A[r] = A[k]
        A[k]=b
        for j in range(l):
            if j != r:
                c = A[j][q]
                for k in range(l+1):
                    A[j][k] = (A[j][k] + c*A[r][k])%2
        r +=1
        q+=1
    for i in range(r, l):
        if A[i][l] !=0:
            print("この行列は零行列にできない.")
            return -1

    s = l - r
    C = [0]*s
    t=0
    for i in range(l):
        if A[i][i]==0:
            C[t]= i
            t+=1

    D = [0]*l
    for i in range(l):
        D[i] = A[i][l]
    
    ans=10**9
    for box in itertools.product([0,1], repeat=s):
        E = copy.deepcopy(D)
        for i in range(len(box)):
            if box[i]==1:
                for k in range(l):
                    E[k]=(E[k] + A[k][C[i]])%2
                E[C[i]]+=1
        ans = min(ans, sum(E))
    print("零行列にすることができ, 最小の操作回数は"+str(ans))
    for box in itertools.product([0,1], repeat=s):
        E = copy.deepcopy(D)
        for i in range(len(box)):
            if box[i]==1:
                for k in range(l):
                    E[k]=(E[k] + A[k][C[i]])%2
                E[C[i]]+=1
        if sum(E)==ans:
            print("操作手順は例えば以下の通り")
            for a in range(len(E)):
                if E[a]==1:
                    i = a//N
                    j = a % N
                    print("("+str(i+1)+","+str(j+1)+")成分に操作を行う.")
            
    
    return ans

N=4
l = N**2
S = [[0]*N for i in range(N)]
for i in range(N):
    S[i][0]=1
    S[0][i]=1
S[N-1][N-1]=1
total = method_linear_solve(S)

零行列にすることができ, 最小の操作回数は6
操作手順は例えば以下の通り
(1,2)成分に操作を行う.
(1,4)成分に操作を行う.
(2,3)成分に操作を行う.
(3,1)成分に操作を行う.
(3,3)成分に操作を行う.
(4,4)成分に操作を行う.
操作手順は例えば以下の通り
(1,1)成分に操作を行う.
(2,3)成分に操作を行う.
(2,4)成分に操作を行う.
(3,2)成分に操作を行う.
(4,2)成分に操作を行う.
(4,4)成分に操作を行う.
操作手順は例えば以下の通り
(1,3)成分に操作を行う.
(2,1)成分に操作を行う.
(3,2)成分に操作を行う.
(3,3)成分に操作を行う.
(4,1)成分に操作を行う.
(4,4)成分に操作を行う.
操作手順は例えば以下の通り
(1,1)成分に操作を行う.
(1,4)成分に操作を行う.
(3,4)成分に操作を行う.
(4,1)成分に操作を行う.
(4,3)成分に操作を行う.
(4,4)成分に操作を行う.


と言うことで実際に試してみるとこんな感じ

In [27]:
N=10
l = N**2
S = [[1,1,1,0,0,0,0,0,0,1],[1,1,1,0,0,0,0,0,1,0],[1,1,0,0,0,0,0,0,1,0],
     [0,0,0,0,0,1,1,0,0,1],[0,0,1,0,1,0,1,1,0,0],[0,1,1,0,0,0,0,1,1,0],
     [0,0,0,1,1,0,1,1,0,1],[0,0,0,1,0,0,0,1,0,0],[1,0,0,0,0,0,0,0,0,1],
     [1,1,0,0,0,0,0,0,0,1]]   
print(*S, sep='\n')
total = method_linear_solve(S)

[1, 1, 1, 0, 0, 0, 0, 0, 0, 1]
[1, 1, 1, 0, 0, 0, 0, 0, 1, 0]
[1, 1, 0, 0, 0, 0, 0, 0, 1, 0]
[0, 0, 0, 0, 0, 1, 1, 0, 0, 1]
[0, 0, 1, 0, 1, 0, 1, 1, 0, 0]
[0, 1, 1, 0, 0, 0, 0, 1, 1, 0]
[0, 0, 0, 1, 1, 0, 1, 1, 0, 1]
[0, 0, 0, 1, 0, 0, 0, 1, 0, 0]
[1, 0, 0, 0, 0, 0, 0, 0, 0, 1]
[1, 1, 0, 0, 0, 0, 0, 0, 0, 1]
零行列にすることができ, 最小の操作回数は15
操作手順は例えば以下の通り
(1,1)成分に操作を行う.
(1,2)成分に操作を行う.
(2,1)成分に操作を行う.
(2,2)成分に操作を行う.
(2,10)成分に操作を行う.
(3,10)成分に操作を行う.
(5,6)成分に操作を行う.
(5,7)成分に操作を行う.
(6,3)成分に操作を行う.
(6,7)成分に操作を行う.
(7,4)成分に操作を行う.
(7,9)成分に操作を行う.
(8,9)成分に操作を行う.
(9,10)成分に操作を行う.
(10,1)成分に操作を行う.


このプログラムはどれくらい時間がかかるのだろうか. ちょっと確かめてみた.

In [53]:
import time
for N in range(1,20):
    s=time.time()
    l = N**2
    S = [[1]*N for i in range(N)]
    total = linear_solve(S)
    t = time.time()
    print(str(N)+"次正方行列について,"+str(t-s)+"秒かかった")

零行列にすることができ, 最小の操作回数は1
1次正方行列について,0.00020313262939453125秒かかった
零行列にすることができ, 最小の操作回数は4
2次正方行列について,8.797645568847656e-05秒かかった
零行列にすることができ, 最小の操作回数は5
3次正方行列について,0.00026488304138183594秒かかった
零行列にすることができ, 最小の操作回数は4
4次正方行列について,0.0012369155883789062秒かかった
零行列にすることができ, 最小の操作回数は15
5次正方行列について,0.0035698413848876953秒かかった
零行列にすることができ, 最小の操作回数は28
6次正方行列について,0.011835336685180664秒かかった
零行列にすることができ, 最小の操作回数は33
7次正方行列について,0.027331113815307617秒かかった
零行列にすることができ, 最小の操作回数は40
8次正方行列について,0.05190300941467285秒かかった
零行列にすることができ, 最小の操作回数は25
9次正方行列について,0.10956001281738281秒かかった
零行列にすることができ, 最小の操作回数は44
10次正方行列について,0.18737506866455078秒かかった
零行列にすることができ, 最小の操作回数は55
11次正方行列について,0.2858281135559082秒かかった
零行列にすることができ, 最小の操作回数は72
12次正方行列について,0.5038070678710938秒かかった
零行列にすることができ, 最小の操作回数は105
13次正方行列について,0.8073768615722656秒かかった
零行列にすることができ, 最小の操作回数は56
14次正方行列について,1.2933008670806885秒かかった
零行列にすることができ, 最小の操作回数は117
15次正方行列について,1.9361109733581543秒かかった
零行列にすることができ, 最小の操作回数は104
16次正方行列について,2.8808751106262207秒かかった
零行列にすることができ, 最小の操作回数は147
1

ちなみにライツアウトに関して, $n$の値によって解が常に存在する時としない時がある. 
これって理論的に分かっているのだろうか?　一応気になって調べてみたが規則性はわからなかったので詳しいことを知っている人は教えてほしい.

In [30]:
def linear_rank(N):
    l = N**2
    A = [[0]*l for i in range(l)]
    for a in range (l):
        i = a // N
        j = a % N  
        A[a][a]=1
        A[max(a-1,i*N)][a] = 1
        A[min(a+1,i*N + (N-1))][a] = 1
        if a > N-1:
            A[a-N][a] = 1
        if a < N*(N-1):
            A[a+N][a] = 1

    # l*l+1行列の掃きだし法
    r =0
    q=0
    while q <l:
        flag =True
        for k in range(r,l):
            if A[k][q]!=0:
                flag =False
                break
        if flag:
            q += 1
            continue
        b=A[r]
        A[r] = A[k]
        A[k]=b
        for j in range(l):
            if j != r:
                c = A[j][q]
                for k in range(l):
                    A[j][k] = (A[j][k] + c*A[r][k])%2
        r +=1
        q+=1
    return r
for i in range(1,20):
    r = linear_rank(i)
    print(i,i**2, r)

1 1 1
2 4 4
3 9 9
4 16 12
5 25 23
6 36 36
7 49 49
8 64 64
9 81 73
10 100 100
11 121 115
12 144 144
13 169 169
14 196 192
15 225 225
16 256 248
17 289 287
18 324 324
19 361 345
